steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - python-http-function
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python312